branches:
  only:
    - master
    - /^\d\.\d\.\d$/

os: osx

language: node_js
node_js:
  - "15"

stages:
  - lint
  - build
  - test
  - release

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - yarn

jobs:
  allow_failures:
    - os: linux
  include:
    - os: linux
      dist: xenial
    - stage: lint
      script: tslint -c tslint.json 'src/**/*.ts'
      os: linux
    - stage: build
      script: npm run vscode:prepublish
      os: linux
    - stage: test
      script: npm run test
      os: osx
    - stage: release
      script:
        - yarn add vsce -D
        - vsce package --no-yarn
        - ls -alh
      os: linux
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file: "./doxdocgen-$TRAVIS_TAG.vsix"
          skip_cleanup: true
          on:
            tags: true
        - provider: script
          script: vsce publish --no-yarn -p $VSMARKETPLACE_ACCESS_TOKEN
          skip_cleanup: true
          on:
            tags: true

after_success:
  - ./publish_coverage.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/87b3ab4176e6f9506c13
    on_success: always
    on_failure: always
    on_start: never